name: pages-build-deploy
on:
  # workflow_dispatch: 
  push:
    branches:
      - master
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: true
  
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.118.2'
          extended: true

      - name: Build Hugo
        run: hugo -b "https://serialt.github.io/" -e "production"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          deploy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          publish_dir: ./public
          commit_message: ${{ github.event.head_commit.message }}